FROM node:20-alpine

WORKDIR /app
COPY server-package.json ./package.json
RUN npm install
COPY server.js ./
COPY .env* ./
COPY tiger_private_key.pem ./
COPY cmc_portfolio.csv ./

EXPOSE 3001
CMD ["node", "server.js"]
